import React from "react";
import { BookOpen, Bot, Code2 } from "lucide-react";

const Home = () => {
  return (
    <div className="min-h-screen bg-[#0f172a] text-white">
      {/* Hero + Tech Topics */}
      <section className="py-20 px-6 text-center max-w-7xl mx-auto">
        <h1 className="text-4xl md:text-5xl font-bold mb-4">
          Empower Your Learning Journey 🚀
        </h1>
        <p className="text-lg md:text-xl text-gray-300 mb-8 max-w-2xl mx-auto">
          Unlock your potential with AI-powered content, hands-on coding, and
          structured learning tailored just for you.
        </p>
        <a
          href="#features"
          className="bg-orange-500 hover:bg-orange-600 text-white px-6 py-3 rounded-full transition duration-300"
        >
          Explore Features
        </a>

        {/* Tech Topics */}
        <div className="mt-12">
          <h2 className="text-2xl font-semibold mb-6">Start With</h2>
          <div className="flex flex-wrap justify-center gap-4">
            {["HTML", "CSS", "JavaScript", "React", "Java", "DSA", "SQL"].map(
              (topic) => (
                <span
                  key={topic}
                  className="bg-[#1e293b] border border-gray-600 text-gray-300 px-4 py-2 rounded-full text-sm font-medium shadow-sm"
                >
                  {topic}
                </span>
              )
            )}
          </div>
        </div>

        {/* Features */}
        <div
          id="features"
          className="mt-20 grid md:grid-cols-3 gap-8 text-left"
        >
          <div className="bg-[#1e293b] p-6 rounded-2xl shadow hover:shadow-lg transition border border-gray-700">
            <Bot className="w-12 h-12 text-orange-400 mb-4" />
            <h3 className="text-xl font-semibold mb-2">AI-Powered Content</h3>
            <p className="text-gray-400">
              Topic-wise explanations, quizzes, and examples generated by AI.
            </p>
          </div>

          <div className="bg-[#1e293b] p-6 rounded-2xl shadow hover:shadow-lg transition border border-gray-700">
            <Code2 className="w-12 h-12 text-green-400 mb-4" />
            <h3 className="text-xl font-semibold mb-2">
              Real-Time Code Execution
            </h3>
            <p className="text-gray-400">
              Practice code with Judge0 API and get instant output.
            </p>
          </div>

          <div className="bg-[#1e293b] p-6 rounded-2xl shadow hover:shadow-lg transition border border-gray-700">
            <BookOpen className="w-12 h-12 text-purple-400 mb-4" />
            <h3 className="text-xl font-semibold mb-2">
              Personalized Learning
            </h3>
            <p className="text-gray-400">
              Topic flow and content tailored for your academic level.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Home;
